import React, { useState, useEffect } from "react";
import { onAuthStateChanged, signOut, User } from "firebase/auth";
import { collection, doc, setDoc, deleteDoc, updateDoc, onSnapshot, getDoc } from "firebase/firestore";
import { auth, db, handleFirestoreError, OperationType } from "./lib/firebase";
import { BankAccount, Transaction, Budget } from "./types";

// Components
import Login from "./components/Login";
import Dashboard from "./components/Dashboard";
import Transactions from "./components/Transactions";
import Budgets from "./components/Budgets";
import BankSync from "./components/BankSync";
import AIAdvisor from "./components/AIAdvisor";

// Icons
import {
  Landmark,
  LogOut,
  LayoutDashboard,
  ArrowLeftRight,
  TrendingUp,
  BrainCircuit,
  ChevronRight,
  ShieldAlert,
  Loader2,
  Menu,
  X,
  PiggyBank
} from "lucide-react";

// Preset initial sandbox data for Demo Mode
const PRESET_ACCOUNTS: BankAccount[] = [
  {
    id: "acc_demo_nubank",
    bankName: "Nubank",
    accountNumber: "0001 / 823451-2",
    accountType: "Conta Corrente",
    balance: 2850.50,
    status: "active",
    lastSyncedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "acc_demo_itau",
    bankName: "Itaú",
    accountNumber: "0300 / 12844-9",
    accountType: "Conta Corrente",
    balance: 15400.00,
    status: "active",
    lastSyncedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  }
];

const PRESET_TRANSACTIONS: Transaction[] = [
  {
    id: "tx_demo_1",
    description: "Salário Mensal",
    amount: 6500.00,
    type: "income",
    category: "Salário",
    date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    bankAccountId: "acc_demo_itau",
    bankName: "Itaú",
    source: "Open Finance API",
    createdAt: new Date().toISOString(),
  },
  {
    id: "tx_demo_2",
    description: "Aluguel Apartamento",
    amount: 1500.00,
    type: "expense",
    category: "Moradia",
    date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    bankAccountId: "acc_demo_itau",
    bankName: "Itaú",
    source: "Open Finance API",
    createdAt: new Date().toISOString(),
  },
  {
    id: "tx_demo_3",
    description: "Supermercado Pão de Açúcar",
    amount: 420.50,
    type: "expense",
    category: "Alimentação",
    date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    bankAccountId: "acc_demo_nubank",
    bankName: "Nubank",
    source: "Open Finance API",
    createdAt: new Date().toISOString(),
  },
  {
    id: "tx_demo_4",
    description: "Netflix Assinatura",
    amount: 55.90,
    type: "expense",
    category: "Serviços/Assinaturas",
    date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    bankAccountId: "acc_demo_nubank",
    bankName: "Nubank",
    source: "Open Finance API",
    createdAt: new Date().toISOString(),
  },
  {
    id: "tx_demo_5",
    description: "Gasolina Shell",
    amount: 150.00,
    type: "expense",
    category: "Transporte",
    date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    bankAccountId: "acc_demo_nubank",
    bankName: "Nubank",
    source: "Open Finance API",
    createdAt: new Date().toISOString(),
  },
];

const PRESET_BUDGETS: Budget[] = [
  { id: "b_demo_1", category: "Moradia", limit: 2000, spent: 1500, month: new Date().toISOString().substring(0, 7), autoGenerated: true, createdAt: new Date().toISOString() },
  { id: "b_demo_2", category: "Alimentação", limit: 1000, spent: 420.50, month: new Date().toISOString().substring(0, 7), autoGenerated: true, createdAt: new Date().toISOString() },
  { id: "b_demo_3", category: "Transporte", limit: 500, spent: 150.00, month: new Date().toISOString().substring(0, 7), autoGenerated: true, createdAt: new Date().toISOString() },
  { id: "b_demo_4", category: "Lazer", limit: 400, spent: 0, month: new Date().toISOString().substring(0, 7), autoGenerated: true, createdAt: new Date().toISOString() },
  { id: "b_demo_5", category: "Serviços/Assinaturas", limit: 200, spent: 55.90, month: new Date().toISOString().substring(0, 7), autoGenerated: true, createdAt: new Date().toISOString() },
  { id: "b_demo_6", category: "Outros", limit: 300, spent: 0, month: new Date().toISOString().substring(0, 7), autoGenerated: true, createdAt: new Date().toISOString() },
];

export default function App() {
  const [currentUser, setCurrentUser] = useState<User | null>(null);
  const [authLoading, setAuthLoading] = useState(true);
  const [isDemo, setIsDemo] = useState(false);

  // Financial App State
  const [accounts, setAccounts] = useState<BankAccount[]>([]);
  const [transactions, setTransactions] = useState<Transaction[]>([]);
  const [budgets, setBudgets] = useState<Budget[]>([]);
  
  // UI States
  const [activeTab, setActiveTab] = useState<"dashboard" | "transactions" | "budgets" | "banks" | "advisor">("dashboard");
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [isLinkingBank, setIsLinkingBank] = useState(false);
  const [isSyncingBank, setIsSyncingBank] = useState(false);
  const [isGeneratingAI, setIsGeneratingAI] = useState(false);
  const [aiExplanation, setAiExplanation] = useState<string>("");

  // Listen to Auth State
  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, (user) => {
      setCurrentUser(user);
      setAuthLoading(false);
      if (user) {
        setIsDemo(false);
      }
    });
    return () => unsubscribe();
  }, []);

  // Sync data from local storage or Firestore
  useEffect(() => {
    if (isDemo) {
      // Load from LocalStorage
      const storedAcc = localStorage.getItem("demo_accounts");
      const storedTx = localStorage.getItem("demo_transactions");
      const storedBudgets = localStorage.getItem("demo_budgets");
      const storedExplanation = localStorage.getItem("demo_explanation");

      if (storedAcc && storedTx && storedBudgets) {
        setAccounts(JSON.parse(storedAcc));
        setTransactions(JSON.parse(storedTx));
        setBudgets(JSON.parse(storedBudgets));
        if (storedExplanation) setAiExplanation(storedExplanation);
      } else {
        // Init with high-fidelity preset
        setAccounts(PRESET_ACCOUNTS);
        setTransactions(PRESET_TRANSACTIONS);
        setBudgets(PRESET_BUDGETS);
        setAiExplanation("Bem-vindo ao Modo Demonstração! Sinta-se à vontade para conectar contas bancárias simuladas e ajustar orçamentos via inteligência artificial.");
      }
    } else if (currentUser) {
      // Load in real-time from Firestore
      const userId = currentUser.uid;

      // Ensure Root User doc exists
      const userRef = doc(db, "users", userId);
      getDoc(userRef).then((snapshot) => {
        if (!snapshot.exists()) {
          setDoc(userRef, {
            uid: userId,
            email: currentUser.email,
            displayName: currentUser.displayName || "",
            createdAt: new Date().toISOString()
          }).catch(err => handleFirestoreError(err, OperationType.WRITE, `users/${userId}`));
        }
      });

      // Listen to bank accounts
      const accountsUnsubscribe = onSnapshot(collection(db, "users", userId, "bankAccounts"), (snapshot) => {
        const list: BankAccount[] = [];
        snapshot.forEach(doc => list.push(doc.data() as BankAccount));
        setAccounts(list);
      }, (error) => handleFirestoreError(error, OperationType.LIST, `users/${userId}/bankAccounts`));

      // Listen to transactions
      const txUnsubscribe = onSnapshot(collection(db, "users", userId, "transactions"), (snapshot) => {
        const list: Transaction[] = [];
        snapshot.forEach(doc => list.push(doc.data() as Transaction));
        // Sort by date descending
        list.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
        setTransactions(list);
      }, (error) => handleFirestoreError(error, OperationType.LIST, `users/${userId}/transactions`));

      // Listen to budgets
      const budgetsUnsubscribe = onSnapshot(collection(db, "users", userId, "budgets"), (snapshot) => {
        const list: Budget[] = [];
        snapshot.forEach(doc => list.push(doc.data() as Budget));
        setBudgets(list);
      }, (error) => handleFirestoreError(error, OperationType.LIST, `users/${userId}/budgets`));

      return () => {
        accountsUnsubscribe();
        txUnsubscribe();
        budgetsUnsubscribe();
      };
    }
  }, [currentUser, isDemo]);

  // Persist Demo State Changes to LocalStorage
  useEffect(() => {
    if (isDemo) {
      localStorage.setItem("demo_accounts", JSON.stringify(accounts));
      localStorage.setItem("demo_transactions", JSON.stringify(transactions));
      localStorage.setItem("demo_budgets", JSON.stringify(budgets));
      localStorage.setItem("demo_explanation", aiExplanation);
    }
  }, [accounts, transactions, budgets, aiExplanation, isDemo]);

  // Actions: Add Transaction
  const handleAddTransaction = async (txData: Omit<Transaction, "id" | "createdAt">) => {
    const txId = `tx_${Math.random().toString(36).substring(2, 9)}`;
    const newTx: Transaction = {
      ...txData,
      id: txId,
      createdAt: new Date().toISOString()
    };

    if (isDemo) {
      setTransactions(prev => [newTx, ...prev]);
      // Update account balance
      if (txData.bankAccountId) {
        setAccounts(prev => prev.map(acc => {
          if (acc.id === txData.bankAccountId) {
            const mod = txData.type === "income" ? txData.amount : -txData.amount;
            return { ...acc, balance: Number((acc.balance + mod).toFixed(2)) };
          }
          return acc;
        }));
      }
    } else if (currentUser) {
      const path = `users/${currentUser.uid}/transactions/${txId}`;
      try {
        await setDoc(doc(db, "users", currentUser.uid, "transactions", txId), newTx);
        // If linked to account, update balance
        if (txData.bankAccountId) {
          const accRef = doc(db, "users", currentUser.uid, "bankAccounts", txData.bankAccountId);
          const accSnap = await getDoc(accRef);
          if (accSnap.exists()) {
            const currentBal = accSnap.data().balance || 0;
            const mod = txData.type === "income" ? txData.amount : -txData.amount;
            await updateDoc(accRef, { balance: Number((currentBal + mod).toFixed(2)) });
          }
        }
      } catch (err) {
        handleFirestoreError(err, OperationType.WRITE, path);
      }
    }
  };

  // Actions: Delete Transaction
  const handleDeleteTransaction = async (id: string) => {
    const target = transactions.find(t => t.id === id);

    if (isDemo) {
      setTransactions(prev => prev.filter(t => t.id !== id));
      // Revert account balance
      if (target && target.bankAccountId) {
        setAccounts(prev => prev.map(acc => {
          if (acc.id === target.bankAccountId) {
            const mod = target.type === "income" ? -target.amount : target.amount;
            return { ...acc, balance: Number((acc.balance + mod).toFixed(2)) };
          }
          return acc;
        }));
      }
    } else if (currentUser && target) {
      const path = `users/${currentUser.uid}/transactions/${id}`;
      try {
        await deleteDoc(doc(db, "users", currentUser.uid, "transactions", id));
        // Revert account balance
        if (target.bankAccountId) {
          const accRef = doc(db, "users", currentUser.uid, "bankAccounts", target.bankAccountId);
          const accSnap = await getDoc(accRef);
          if (accSnap.exists()) {
            const currentBal = accSnap.data().balance || 0;
            const mod = target.type === "income" ? -target.amount : target.amount;
            await updateDoc(accRef, { balance: Number((currentBal + mod).toFixed(2)) });
          }
        }
      } catch (err) {
        handleFirestoreError(err, OperationType.WRITE, path);
      }
    }
  };

  // Actions: Update Budget Meta
  const handleUpdateBudget = async (id: string, limit: number) => {
    if (isDemo) {
      setBudgets(prev => prev.map(b => b.id === id ? { ...b, limit, autoGenerated: false } : b));
    } else if (currentUser) {
      const path = `users/${currentUser.uid}/budgets/${id}`;
      try {
        await updateDoc(doc(db, "users", currentUser.uid, "budgets", id), { limit, autoGenerated: false });
      } catch (err) {
        handleFirestoreError(err, OperationType.WRITE, path);
      }
    }
  };

  // Actions: Link Bank Account (Trigger API backend)
  const handleLinkBankAccount = async (bankName: string, accountNumber: string, accountType: string) => {
    setIsLinkingBank(true);
    try {
      const response = await fetch("/api/bank/link", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ bankName, accountNumber, accountType })
      });

      if (!response.ok) throw new Error("API Link failed.");

      const result = await response.json();
      const linkedAccount: BankAccount = result.account;
      const initialTransactions: Transaction[] = result.transactions;

      if (isDemo) {
        setAccounts(prev => [...prev, linkedAccount]);
        setTransactions(prev => [...initialTransactions, ...prev]);
      } else if (currentUser) {
        // Save Account to Firestore
        await setDoc(doc(db, "users", currentUser.uid, "bankAccounts", linkedAccount.id), linkedAccount);
        // Save initial seed transactions to Firestore
        for (const tx of initialTransactions) {
          await setDoc(doc(db, "users", currentUser.uid, "transactions", tx.id), tx);
        }
      }
    } catch (err) {
      console.error("Open Finance linkage failed:", err);
      alert("Conexão falhou. Tente novamente mais tarde.");
    } finally {
      setIsLinkingBank(false);
    }
  };

  // Actions: Sync Account Balance (Trigger API backend)
  const handleSyncBankAccount = async (accountId: string, bankName: string, currentBalance: number) => {
    setIsSyncingBank(true);
    try {
      const response = await fetch("/api/bank/sync", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ accountId, bankName, currentBalance })
      });

      if (!response.ok) throw new Error("API Sync failed.");

      const result = await response.json();
      const newTransactions: Transaction[] = result.transactions;
      const updatedBalance: number = result.updatedBalance;

      if (isDemo) {
        // Update account balance
        setAccounts(prev => prev.map(acc => acc.id === accountId ? { ...acc, balance: updatedBalance, lastSyncedAt: result.syncedAt } : acc));
        // Append new transactions
        setTransactions(prev => [...newTransactions, ...prev]);
      } else if (currentUser) {
        // Write account update
        await updateDoc(doc(db, "users", currentUser.uid, "bankAccounts", accountId), {
          balance: updatedBalance,
          lastSyncedAt: result.syncedAt
        });
        // Save new transactions
        for (const tx of newTransactions) {
          await setDoc(doc(db, "users", currentUser.uid, "transactions", tx.id), tx);
        }
      }
    } catch (err) {
      console.error("Open Finance sync failed:", err);
    } finally {
      setIsSyncingBank(false);
    }
  };

  // Actions: Synchronize all bank accounts in parallel
  const handleSyncAllAccounts = async () => {
    if (accounts.length === 0) {
      alert("Nenhuma conta vinculada para sincronizar.");
      return;
    }
    setIsSyncingBank(true);
    try {
      for (const acc of accounts) {
        await handleSyncBankAccount(acc.id, acc.bankName, acc.balance);
      }
    } finally {
      setIsSyncingBank(false);
    }
  };

  // Actions: Generate AI Budget allocation (Trigger Gemini API)
  const handleGenerateAIBudget = async (monthlyIncomeGoal: number) => {
    setIsGeneratingAI(true);
    try {
      const response = await fetch("/api/ai/budget", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ transactions, monthlyIncomeGoal })
      });

      if (!response.ok) throw new Error("Budget API failed.");

      const result = await response.json();
      const rawBudgets = result.budgets;
      setAiExplanation(result.explanation);

      // Convert response budgets to system format
      const formattedBudgets: Budget[] = rawBudgets.map((b: any, idx: number) => ({
        id: `b_${idx}_ai_${Math.random().toString(36).substring(2, 6)}`,
        category: b.category,
        limit: Number(b.limit),
        spent: 0,
        month: new Date().toISOString().substring(0, 7),
        autoGenerated: true,
        aiExplanation: result.explanation,
        createdAt: new Date().toISOString()
      }));

      if (isDemo) {
        setBudgets(formattedBudgets);
      } else if (currentUser) {
        // Clear old budgets from current month first or write/overwrite
        for (const b of formattedBudgets) {
          await setDoc(doc(db, "users", currentUser.uid, "budgets", b.category), b);
        }
      }
    } catch (err) {
      console.error("IA budgeting failed:", err);
      alert("Ocorreu um erro ao chamar a Inteligência Artificial. Usando cálculo local padrão.");
    } finally {
      setIsGeneratingAI(false);
    }
  };

  const handleLogout = () => {
    if (isDemo) {
      setIsDemo(false);
      setAccounts([]);
      setTransactions([]);
      setBudgets([]);
    } else {
      signOut(auth);
    }
  };

  // Authentication Guard
  if (authLoading) {
    return (
      <div className="min-h-screen bg-[#0A0B0D] flex flex-col items-center justify-center p-4">
        <Loader2 className="w-8 h-8 text-emerald-500 animate-spin" />
        <span className="text-xs text-gray-400 font-semibold mt-3">Carregando carteira digital...</span>
      </div>
    );
  }

  if (!currentUser && !isDemo) {
    return <Login onEnterDemo={() => setIsDemo(true)} />;
  }

  return (
    <div className="min-h-screen bg-[#0A0B0D] text-[#E0E0E0] flex flex-col md:flex-row font-sans">
      
      {/* LEFT COLUMN: Sidebar Navigation */}
      <aside className="w-full md:w-64 bg-[#0A0B0D] text-[#E0E0E0] flex flex-col shrink-0 border-r border-[#1F2124]">
        
        {/* Sidebar Header */}
        <div className="p-5 border-b border-[#1F2124] flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="p-2 bg-emerald-500/10 rounded-lg text-emerald-400">
              <PiggyBank className="w-6 h-6" />
            </div>
            <div>
              <span className="font-extrabold text-white text-sm block tracking-tight">Finanças IA</span>
              <span className="text-[10px] text-emerald-400 font-semibold block">Open Finance Sincronizado</span>
            </div>
          </div>
          <button
            onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
            className="md:hidden p-1.5 hover:bg-[#1F2124] text-white rounded-lg transition-colors cursor-pointer"
          >
            {mobileMenuOpen ? <X className="w-5 h-5" /> : <Menu className="w-5 h-5" />}
          </button>
        </div>

        {/* Sidebar Nav Links */}
        <nav className={`p-4 flex-1 space-y-1 md:block ${mobileMenuOpen ? "block" : "hidden"}`}>
          
          <button
            onClick={() => { setActiveTab("dashboard"); setMobileMenuOpen(false); }}
            className={`w-full flex items-center gap-3 px-3.5 py-2.5 rounded-xl text-xs font-bold transition-all cursor-pointer ${
              activeTab === "dashboard" ? "bg-[#1F2124] text-emerald-400 border border-[#2D3035]/60 shadow-sm" : "text-gray-500 hover:text-white hover:bg-[#111215]/50"
            }`}
          >
            <LayoutDashboard className="w-4 h-4" />
            Painel Consolidado
          </button>

          <button
            onClick={() => { setActiveTab("transactions"); setMobileMenuOpen(false); }}
            className={`w-full flex items-center gap-3 px-3.5 py-2.5 rounded-xl text-xs font-bold transition-all cursor-pointer ${
              activeTab === "transactions" ? "bg-[#1F2124] text-emerald-400 border border-[#2D3035]/60 shadow-sm" : "text-gray-500 hover:text-white hover:bg-[#111215]/50"
            }`}
          >
            <ArrowLeftRight className="w-4 h-4" />
            Transações
          </button>

          <button
            onClick={() => { setActiveTab("budgets"); setMobileMenuOpen(false); }}
            className={`w-full flex items-center gap-3 px-3.5 py-2.5 rounded-xl text-xs font-bold transition-all cursor-pointer ${
              activeTab === "budgets" ? "bg-[#1F2124] text-emerald-400 border border-[#2D3035]/60 shadow-sm" : "text-gray-500 hover:text-white hover:bg-[#111215]/50"
            }`}
          >
            <TrendingUp className="w-4 h-4" />
            Orçamentos Inteligentes
          </button>

          <button
            onClick={() => { setActiveTab("banks"); setMobileMenuOpen(false); }}
            className={`w-full flex items-center gap-3 px-3.5 py-2.5 rounded-xl text-xs font-bold transition-all cursor-pointer ${
              activeTab === "banks" ? "bg-[#1F2124] text-emerald-400 border border-[#2D3035]/60 shadow-sm" : "text-gray-500 hover:text-white hover:bg-[#111215]/50"
            }`}
          >
            <Landmark className="w-4 h-4" />
            Conexão Open Finance
          </button>

          <button
            onClick={() => { setActiveTab("advisor"); setMobileMenuOpen(false); }}
            className={`w-full flex items-center gap-3 px-3.5 py-2.5 rounded-xl text-xs font-bold transition-all cursor-pointer ${
              activeTab === "advisor" ? "bg-[#1F2124] text-emerald-400 border border-[#2D3035]/60 shadow-sm" : "text-gray-500 hover:text-white hover:bg-[#111215]/50"
            }`}
          >
            <BrainCircuit className="w-4 h-4" />
            Consultor Gemini IA
          </button>

        </nav>

        {/* Sidebar Footer: User Details */}
        <div className="p-4 border-t border-[#1F2124] bg-[#111215]/20 text-xs">
          <div className="flex items-center justify-between">
            <div className="min-w-0 pr-2">
              <span className="block font-bold text-white truncate text-[11px]">
                {isDemo ? "Usuário de Teste" : currentUser?.email}
              </span>
              <span className="block text-[9px] text-emerald-400 font-bold uppercase tracking-wider mt-0.5">
                {isDemo ? "Modo Demo" : "Conta Ativa"}
              </span>
            </div>
            <button
              onClick={handleLogout}
              className="p-2 hover:bg-[#1F2124] hover:text-rose-400 rounded-lg transition-colors cursor-pointer"
              title="Sair do aplicativo"
            >
              <LogOut className="w-4 h-4" />
            </button>
          </div>
        </div>

      </aside>

      {/* RIGHT COLUMN: Active Panel View */}
      <main className="flex-1 p-6 md:p-8 overflow-y-auto space-y-6 bg-[#0A0B0D]">
        
        {/* Render Active Tab */}
        {activeTab === "dashboard" && (
          <Dashboard
            transactions={transactions}
            accounts={accounts}
            budgets={budgets}
            onNavigate={setActiveTab}
            onSyncAll={handleSyncAllAccounts}
            isSyncing={isSyncingBank}
          />
        )}

        {activeTab === "transactions" && (
          <Transactions
            transactions={transactions}
            accounts={accounts}
            onAddTransaction={handleAddTransaction}
            onDeleteTransaction={handleDeleteTransaction}
          />
        )}

        {activeTab === "budgets" && (
          <Budgets
            budgets={budgets}
            transactions={transactions}
            onUpdateBudget={handleUpdateBudget}
            onGenerateAIBudget={handleGenerateAIBudget}
            isGeneratingAI={isGeneratingAI}
            aiExplanation={aiExplanation}
          />
        )}

        {activeTab === "banks" && (
          <BankSync
            accounts={accounts}
            onLinkAccount={handleLinkBankAccount}
            onSyncAccount={handleSyncBankAccount}
            onDeleteAccount={(id) => {
              if (isDemo) {
                setAccounts(prev => prev.filter(a => a.id !== id));
              } else if (currentUser) {
                deleteDoc(doc(db, "users", currentUser.uid, "bankAccounts", id))
                  .catch(err => handleFirestoreError(err, OperationType.WRITE, `users/${currentUser.uid}/bankAccounts/${id}`));
              }
            }}
            isLinking={isLinkingBank}
            isSyncing={isSyncingBank}
          />
        )}

        {activeTab === "advisor" && (
          <AIAdvisor
            transactions={transactions}
            accounts={accounts}
            budgets={budgets}
          />
        )}

      </main>

    </div>
  );
}
