export interface UserProfile {
  uid: string;
  email: string;
  displayName?: string;
  createdAt: string;
}

export interface BankAccount {
  id: string;
  bankName: "Nubank" | "Itaú" | "Bradesco" | "Banco do Brasil" | "Inter" | string;
  accountType: string;
  balance: number;
  accountNumber: string;
  status: "active" | "error";
  lastSyncedAt?: string;
  createdAt: string;
}

export interface Transaction {
  id: string;
  description: string;
  amount: number;
  type: "income" | "expense";
  category: string;
  date: string; // YYYY-MM-DD
  bankAccountId?: string;
  bankName?: string;
  source?: string;
  createdAt: string;
}

export interface Budget {
  id: string;
  category: string;
  limit: number;
  spent: number;
  month: string; // YYYY-MM
  autoGenerated?: boolean;
  aiExplanation?: string;
  createdAt: string;
}
